# Day-28

In [2]:
import numpy as np      # everything starts from

In [16]:
a = np.array([1,2,3])

In [17]:
type(a)

numpy.ndarray

In [18]:
a.ndim      # dimension of the array

1

In [19]:
a.shape     # shape of the array

(3,)

In [20]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# since it's written on C, it takes only less time comapring with any of the python operations
%timeit np.arange(10)**2
%timeit [i**2 for i in range(10)]

823 ns ± 4.71 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
1.77 µs ± 25.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [22]:
# visit every element of an array and performs the operation

print(a)
print(a + 1)
print(a * 2)
print(-a)
print(a**2)

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  3  4  5  6  7  8  9 10 11]
[ 2  4  6  8 10 12 14 16 18 20]
[ -1  -2  -3  -4  -5  -6  -7  -8  -9 -10]
[  1   4   9  16  25  36  49  64  81 100]


In [23]:
np.array([1, 2, 3, '4'], dtype='int')

array([1, 2, 3, 4])

In [24]:
a.dtype

dtype('int32')

# Day-29

In [1]:
# only with numpy array 0.5 increments/step is possible
np.arange(1, 10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [2]:
range(1, 10, 0.5)

TypeError: 'float' object cannot be interpreted as an integer

In [7]:
# indexing with np arrays
a = np.arange(1, 11)

print(a)
print(a[0])
print(a[-2])
print(a[[2, -2]])       # more than one elements at a time


[ 1  2  3  4  5  6  7  8  9 10]
1
9
[3 9]


In [13]:
# slicing
print(a[1 : 5])
print(a[1 : 8 : 2])
print(a[1 : -3 : 3])
print(a[-1 : 3 : -1])

[2 3 4 5]
[2 4 6 8]
[2 5]
[10  9  8  7  6  5]


In [19]:
# masking / filtering
print(a[a > 5])                             # goes with binary conditions
print(a[(a % 2 == 0) & (a % 5 == 0)])       # with AND operator
print(a[(a % 2 == 0) | (a % 3 == 0)])       # with OR operator

[ 6  7  8  9 10]
[10]
[ 2  3  4  6  8  9 10]


In [40]:
# assignment
a = np.arange(10)
print(a)
a[2] = -1               # single element
print(a)

a[[3, -2]] = 10         # multiple elements
print(a)

a[(a % 2 == 0)] = 2     # with masking
print(a)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1 -1  3  4  5  6  7  8  9]
[ 0  1 -1 10  4  5  6  7 10  9]
[ 2  1 -1  2  2  5  2  7  2  9]


In [33]:
# Universal functions
a = np.array([5, 7, 2, 1, 3, 9, 4, 6, 8])
print(a)
print(np.sort(a))       # this function creates a shallow copy of the array and doesn't change the original array
print(a)

# object method
print(a)
print(a.sort())       # this function changes the original array and return None
print(a)


[5 7 2 1 3 9 4 6 8]
[1 2 3 4 5 6 7 8 9]
[5 7 2 1 3 9 4 6 8]
[5 7 2 1 3 9 4 6 8]
None
[1 2 3 4 5 6 7 8 9]


In [34]:
## Aggregate functions
print(a)
print(np.mean(a))
print(np.sum(a))
print(np.min(a))
print(np.max(a))

## object methods
print(a.mean())
print(a.sum())
print(a.min())
print(a.max())
print(a)

[1 2 3 4 5 6 7 8 9]
5.0
45
1
9
5.0
45
1
9
[1 2 3 4 5 6 7 8 9]


In [57]:
# Arithmatic operations (for this to be performed, shape of the arrays should be same)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)        # element-wise addition
print(a - b)
print(a * b)
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [58]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 8])

print(a + b)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

## Airbnb's NPS
data-link: https://drive.google.com/file/d/1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK/view?usp=sharing

In [43]:
# 1. Get data

!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK


Downloading...
From: https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
To: c:\Users\ABASL\OneDrive - Vestas Wind Systems A S\Documents\03_Personal\Scaler\Python Libraries\survey.txt

  0%|          | 0.00/2.55k [00:00<?, ?B/s]
100%|██████████| 2.55k/2.55k [00:00<00:00, 2.57MB/s]


In [9]:
source = np.loadtxt("c:\\Users\\ABASL\\OneDrive - Vestas Wind Systems A S\\Documents\\03_Personal\\Scaler\\Python Libraries\\survey.txt", dtype='int')
source

array([ 7, 10,  5, ...,  5,  9, 10])

In [10]:
# 2. Total number of reviews
total = source.shape[0]
total

1167

In [11]:
# 3. Extract promoters and detractors
promoters = source[(source > 8)].shape[0]
detractors = source[(source < 7)].shape[0]


In [12]:
# 4. Calculate Net Promoter Score (NPS)
nps = (promoters * 100 / total) - (detractors * 100 / total)
nps


23.73607540702656

# Day-30

In [20]:
# Empty array
temp = np.empty(source.shape, dtype="<U20")

In [21]:
# Transform integers into meaningful strings
temp[source > 8] = "Promoters"
temp[source < 7] = "Detractors"
temp[(source == 7) | (source == 8)] = "Passive"
temp

array(['Passive', 'Promoters', 'Detractors', ..., 'Detractors',
       'Promoters', 'Promoters'], dtype='<U20')

In [28]:
# Get Uniques
np.unique(temp)     # without counts
categ, count = np.unique(temp, return_counts=True)      # with counts
overview = {categ[i]: count[i] for i in range(len(categ))}
overview


{'Detractors': 332, 'Passive': 226, 'Promoters': 609}

## 2D - Arrays (i.e., Matrices)

In [3]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
np.ndim(a)

2

In [5]:
np.shape(a)

(3, 4)

In [6]:
a.T     # transpose

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [7]:
a.reshape(4, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
a.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [9]:
a.reshape(1, 12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [10]:
a.reshape(4, -1)        # -1 for unknown number of row/col value

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Day-32

In [16]:
!gdown 1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd

Downloading...
From: https://drive.google.com/uc?id=1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd
To: c:\Users\ABASL\OneDrive - Vestas Wind Systems A S\Documents\03_Personal\Scaler\Python Libraries\fit.txt

  0%|          | 0.00/3.43k [00:00<?, ?B/s]
100%|██████████| 3.43k/3.43k [00:00<?, ?B/s]


In [19]:
data = np.loadtxt("c:\\Users\\ABASL\\OneDrive - Vestas Wind Systems A S\\Documents\\03_Personal\\Scaler\\Python Libraries\\fit.txt", dtype="str")
# data

# Day-33

In [4]:
a = np.arange(1, 13).reshape(3, 4)
b = np.arange(2, 14).reshape(3, 4)
c = np.arange(1, 13).reshape(4, 3)

In [5]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
b

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [7]:
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
a * b       # element wise multiplication - only possible when the shape of those matrices are same

array([[  2,   6,  12,  20],
       [ 30,  42,  56,  72],
       [ 90, 110, 132, 156]])

In [10]:
# Matrix multiplication
np.matmul(a, c)

array([[ 70,  80,  90],
       [158, 184, 210],
       [246, 288, 330]])

In [11]:
np.matmul(c, a)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128],
       [128, 152, 176, 200],
       [173, 206, 239, 272]])

In [12]:
np.matmul(a, b)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [14]:
a@c     # alias for matmul - operator version

array([[ 70,  80,  90],
       [158, 184, 210],
       [246, 288, 330]])

In [15]:
np.dot(a, c)        # another alias for matmul

array([[ 70,  80,  90],
       [158, 184, 210],
       [246, 288, 330]])

# Day-35

In [3]:
np.split?

Signature: np.split(ary, indices_or_sections, axis=0)
Docstring:
Split an array into multiple sub-arrays as views into `ary`.

Parameters
----------
ary : ndarray
    Array to be divided into sub-arrays.
indices_or_sections : int or 1-D array
    If `indices_or_sections` is an integer, N, the array will be divided
    into N equal arrays along `axis`.  If such a split is not possible,
    an error is raised.

    If `indices_or_sections` is a 1-D array of sorted integers, the entries
    indicate where along `axis` the array is split.  For example,
    ``[2, 3]`` would, for ``axis=0``, result in

      - ary[:2]
      - ary[2:3]
      - ary[3:]

    If an index exceeds the dimension of the array along `axis`,
    an empty sub-array is returned correspondingly.
axis : int, optional
    The axis along which to split, default is 0.

Returns
-------
sub-arrays : list of ndarrays
    A list of sub-arrays as views into `ary`.

Raises
------
ValueError
    If `indices_or_sections` is given as

In [4]:
np.hsplit?

Signature: np.hsplit(ary, indices_or_sections)
Docstring:
Split an array into multiple sub-arrays horizontally (column-wise).

Please refer to the `split` documentation.  `hsplit` is equivalent
to `split` with ``axis=1``, the array is always split along the second
axis regardless of the array dimension.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> x = np.arange(16.0).reshape(4, 4)
>>> x
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
>>> np.hsplit(x, 2)
[array([[  0.,   1.],
       [  4.,   5.],
       [  8.,   9.],
       [12.,  13.]]),
 array([[  2.,   3.],
       [  6.,   7.],
       [10.,  11.],
       [14.,  15.]])]
>>> np.hsplit(x, np.array([3, 6]))
[array([[ 0.,   1.,   2.],
       [ 4.,   5.,   6.],
       [ 8.,   9.,  10.],
       [12.,  13.,  14.]]),
 array([[ 3.],
       [ 7.],
       [11.],
       [15.]]),
 array([], shape=(4, 0), dtyp

In [5]:
np.vsplit?

Signature: np.vsplit(ary, indices_or_sections)
Docstring:
Split an array into multiple sub-arrays vertically (row-wise).

Please refer to the ``split`` documentation.  ``vsplit`` is equivalent
to ``split`` with `axis=0` (default), the array is always split along the
first axis regardless of the array dimension.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> x = np.arange(16.0).reshape(4, 4)
>>> x
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
>>> np.vsplit(x, 2)
[array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])]
>>> np.vsplit(x, np.array([3, 6]))
[array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]]), array([[12., 13., 14., 15.]]), array([], shape=(0, 4), dtype=float64)]

With a higher dimensional array the split is still along the first axis.

>>> x = n

In [6]:
# stacking
np.hstack?

Signature: np.hstack(tup)
Docstring:
Stack arrays in sequence horizontally (column wise).

This is equivalent to concatenation along the second axis, except for 1-D
arrays where it concatenates along the first axis. Rebuilds arrays divided
by `hsplit`.

This function makes most sense for arrays with up to 3 dimensions. For
instance, for pixel-data with a height (first axis), width (second axis),
and r/g/b channels (third axis). The functions `concatenate`, `stack` and
`block` provide more general stacking and concatenation operations.

Parameters
----------
tup : sequence of ndarrays
    The arrays must have the same shape along all but the second axis,
    except 1-D arrays which can be any length.

Returns
-------
stacked : ndarray
    The array formed by stacking the given arrays.

See Also
--------
concatenate : Join a sequence of arrays along an existing axis.
stack : Join a sequence of arrays along a new axis.
block : Assemble an nd-array from nested lists of blocks.
vstack : Sta

In [7]:
np.vstack?

Signature: np.vstack(tup)
Docstring:
Stack arrays in sequence vertically (row wise).

This is equivalent to concatenation along the first axis after 1-D arrays
of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
`vsplit`.

This function makes most sense for arrays with up to 3 dimensions. For
instance, for pixel-data with a height (first axis), width (second axis),
and r/g/b channels (third axis). The functions `concatenate`, `stack` and
`block` provide more general stacking and concatenation operations.

Parameters
----------
tup : sequence of ndarrays
    The arrays must have the same shape along all but the first axis.
    1-D arrays must have the same length.

Returns
-------
stacked : ndarray
    The array formed by stacking the given arrays, will be at least 2-D.

See Also
--------
concatenate : Join a sequence of arrays along an existing axis.
stack : Join a sequence of arrays along a new axis.
block : Assemble an nd-array from nested lists of blocks.
hstac

In [8]:
np.concatenate?

Docstring:
concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
    Controls what kind of data casting may occur. Defaults to 'same_kind'.

    .. versionadded:: 1.20.0

Returns