In [1]:
print("Welcome to Numpy-2")

Welcome to Numpy-2


# Agenda

- **Installing and Importing Numpy**✅
- **Introduction to use case**✅
- **Motivation: Why to use Numpy? - How is it different from Python Lists?**✅
- **Creating a Basic Numpy Array**✅
    - From a List - `array()`, `shape`, `ndim`✅
    - From a range and stepsize - `arange()`✅
    - `type()` ndarray✅
- **How numpy works under the hood?**✅
- **Indexing and Slicing on 1D** ✅
    - Indexing✅
    - Slicing✅
    - Masking (Fancy Indexing)✅
- **Operation on array**✅
- **Universal Functions (ufunc) on 1D array**✅
    - Aggregate Function/ Reduction functions - `sum()`, `mean()`, ✅`min()`, `max()`
- **Usecase: calculate NPS**✅
    - loading data: `np.loadtxt()`✅
    - `np.empty()`
    - `np.unique()`

    
- **2-D arrays (Matrices)**
    - `reshape()`
    - Transpose
    - Converting Matrix back to Vector - `flatten()`


**Indexing and Slicing on 1D** 

    - Indexing
    
    - Slicing
    
    - Masking (Fancy Indexing)

In [3]:
a=np.arange(1,12)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
a[2]

3

In [5]:
a[5]

6

In [6]:
a[-6]

6

In [7]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
[2,6,7,10]

In [8]:
a[[2,6,7,10]]

array([ 3,  7,  8, 11])

In [ ]:
[-9,-5,-4,-1]

In [9]:
a[[-9,-5,-4,-1]]

array([ 3,  7,  8, 11])

In [10]:
a[[2,6,-4,-1]]

array([ 3,  7,  8, 11])

In [11]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
a[2,-9]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
# Slicing 

In [13]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
a[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
a[::]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
a[0:5]

array([1, 2, 3, 4, 5])

In [18]:
a[2:7]

array([3, 4, 5, 6, 7])

In [19]:
a[2:7:2]

array([3, 5, 7])

In [20]:
a[2:7:-1]

array([], dtype=int64)

In [21]:
a[7:2:-1]

array([8, 7, 6, 5, 4])

In [22]:
a[-2:-7:-1]

array([10,  9,  8,  7,  6])

In [23]:
a[-7:-2:-1]

array([], dtype=int64)

In [24]:
a[-2:-7:-2]

array([10,  8,  6])

In [25]:
a[8:-10:-2]

array([9, 7, 5, 3])

In [27]:
# q=[1,2,3,4,5]
# q[[0,1]]

In [28]:
a<6

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False])

In [29]:
a[a<6]

array([1, 2, 3, 4, 5])

In [31]:
mask=(a%2==0)
mask

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [32]:
a[mask]

array([ 2,  4,  6,  8, 10])

In [33]:
a[a%2==0]

array([ 2,  4,  6,  8, 10])

In [34]:
a[~mask]

array([ 1,  3,  5,  7,  9, 11])

In [36]:
a[~(a%2==0)]

array([ 1,  3,  5,  7,  9, 11])

In [37]:
~a

array([ -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12])

In [42]:
mask1=(a%2==0)
mask2=(a%5==0)
print(mask1)
print(mask2)
# And or

[False  True False  True False  True False  True False  True False]
[False False False False  True False False False False  True False]


In [40]:
a[mask1 and mask2]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [41]:
a[mask1 & mask2]

array([10])

In [44]:
# a[mask1] and a[mask2]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [45]:
False and False

False

In [46]:
False and True

False

In [47]:
True and True

True

In [48]:
mask1 and mask2

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [49]:
a[mask1 or mask2]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [50]:
a[mask1 | mask2]

array([ 2,  4,  5,  6,  8, 10])

In [51]:
a==3

array([False, False,  True, False, False, False, False, False, False,
       False, False])

In [52]:
a[a==3]

array([3])

In [53]:
a[(a%2==0)&(a>4)]

array([ 6,  8, 10])

In [57]:
mask=a%2==0
mask

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [58]:
 a[mask | ~mask]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [60]:
# - **Operation on array**
# - **Universal Functions (ufunc) on 1D array**
# #     - Aggregate Function/ Reduction functions - `sum()`, `mean()`, `min()`, `max()`

In [71]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([4,5,6,8])
print(a)
print(b)
print(c)

[1 2 3]
[4 5 6]
[4 5 6 8]


In [62]:
a+b

array([5, 7, 9])

In [64]:
a+c

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [65]:
a-b

array([-3, -3, -3])

In [66]:
a*b

array([ 4, 10, 18])

In [67]:
a/b

array([0.25, 0.4 , 0.5 ])

In [72]:
a%b

array([1, 2, 3])

In [73]:
a=np.arange(1,13)

In [74]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [75]:
np.mean(a)

6.5

In [76]:
np.sum(a)

78

In [77]:
np.max(a)

12

In [78]:
np.min(a)

1

In [79]:
a.min()

1

In [80]:
a.max()

12

In [81]:
a.mean()

6.5

In [82]:
a.sum()

78

In [83]:
a=np.array([5,2,7,8,3,0,1])
a

array([5, 2, 7, 8, 3, 0, 1])

In [84]:
np.sort(a)

array([0, 1, 2, 3, 5, 7, 8])

In [85]:
a

array([5, 2, 7, 8, 3, 0, 1])

In [86]:
a.sort()

In [87]:
a

array([0, 1, 2, 3, 5, 7, 8])

In [ ]:
# 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

In [88]:
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

Downloading...
From: https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
To: /Users/nikhilsanghi/Downloads/01_dsml-course-main-live/batches/1_Aug_Beg_Mon/02_Numpy_2/survey.txt
100%|██████████████████████████████████████| 2.55k/2.55k [00:00<00:00, 2.33MB/s]


In [89]:
score=np.loadtxt("/Users/nikhilsanghi/Downloads/01_dsml-course-main-live/batches/1_Aug_Beg_Mon/02_Numpy_2/survey.txt",dtype='int')

In [90]:
score

array([ 7, 10,  5, ...,  5,  9, 10])

In [93]:
total=score.shape[0]
total

1167

In [94]:
np.max(score)

10

In [95]:
np.min(score)

1

In [96]:
score.shape

(1167,)

In [97]:
a=(1,2,3,4)
a

(1, 2, 3, 4)

In [98]:
type(a)

tuple

In [99]:
a[0]

1

In [100]:
a[1]

2

In [101]:
a[3]

4

In [102]:
total=score.shape[0]
total

1167

In [108]:
detractors=score[score<7].shape[0]
detractors

332

In [113]:
promotors=score[score>8].shape[0]
promotors

609

In [114]:
perc_promotors = (promotors/total)*100
perc_detractors = (detractors/total)*100
print(perc_promotors)
print(perc_detractors)

52.185089974293064
28.449014567266495


In [115]:
nps=perc_promotors-perc_detractors

In [116]:
nps

23.73607540702657

In [117]:
a = np.array([1,2,3,4,5,6,7,8])
print(a.ndim, a.shape)

1 (8,)


In [130]:
a=np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [132]:
a[2:7]=10

In [133]:
a

array([ 1,  2, 10, 10, 10, 10, 10,  8,  9, 10, 11, 12])

In [128]:
a[[1,2,3]] =10

In [129]:
a

array([ 1, 10, 10, 10,  5,  6,  7,  8,  9, 10, 11, 12])

In [123]:
a[a%2==0] =-1

In [124]:
a

array([ 1, -1,  3, -1,  5, -1,  7, -1,  9, -1, 11, -1])

In [136]:
# a = [0,1,2,3,4,5]
# a[4:] = 10

# [0,1,2,3,4,5]

# [0,1,2,3,10,10]
# [0,1,2,3,10,5]

# Error

In [139]:
a = np.array([0,1,2,3,4,5])
a[4:]=10

In [140]:
a

array([ 0,  1,  2,  3, 10, 10])

In [ ]:
a = [1,2,3,4,5]
b = [8,7,6]
a[2:] = b[::-1]

In [ ]:
Error

In [ ]:

[1,2,6,7,8]

In [ ]:
[1,2,8,7,6]


In [ ]:
[1,2,3,4,5,8,7,6]

In [141]:
a = np.array([1,2,3,4,5])
b = np.array([8,7,6])

In [142]:
a

array([1, 2, 3, 4, 5])

In [143]:
b

array([8, 7, 6])

In [144]:
a[2:]

array([3, 4, 5])

In [145]:
b[::-1]

array([6, 7, 8])

In [146]:
a[2:]=b[::-1]

In [147]:
a

array([1, 2, 6, 7, 8])

In [156]:
a = np.array([1,2,3,4,5])
b = np.array([8,7,6,5])
# a[2:]=b[::-1]

In [157]:
a

array([1, 2, 3, 4, 5])

In [158]:
b

array([8, 7, 6, 5])

In [159]:
a[2:]

array([3, 4, 5])

In [160]:
a

array([1, 2, 3, 4, 5])

In [161]:
b[::-1]

array([5, 6, 7, 8])

In [162]:
a[2:]=b[::-1]

ValueError: could not broadcast input array from shape (4,) into shape (3,)

In [ ]:
a = np.array([0,1,2,3,4,5])
mask = (a%2 == 0)
a[mask] = -1

In [ ]:
[0,1,2,3,4,5]

[-1,1,-1,1,-1,1]

Error

[-1,1,-1,3,-1,5]

In [163]:
a = np.array([0,1,2,3,4,5])
a

array([0, 1, 2, 3, 4, 5])

In [164]:
mask = (a%2 == 0)
mask

array([ True, False,  True, False,  True, False])

In [166]:
a[mask] = -1

In [167]:
a

array([-1,  1, -1,  3, -1,  5])

In [172]:
passives=score[(score==7) | (score==8)].shape[0]

In [173]:
passives

226