In [1]:
print("Welcome to Numpy-2-Cont")

Welcome to Numpy-2-Cont


## Agenda

- **Usecase: calculate NPS**✅
    - loading data: `np.loadtxt()`✅
    - `np.empty()`✅
    - `np.unique()`✅


- **Introduction to use case**✅

    
- **2-D arrays (Matrices)**✅
    - `reshape()`
    - 2 Questions✅
    - Transpose✅
    - Converting Matrix back to Vector - `flatten()`✅

- **Indexing and Slicing on 2D** ✅
    - Indexing✅

    - Slicing

    - Masking (Fancy Indexing)




- **Universal Functions (ufunc) on 2D**
    - Aggregate Function/ Reduction functions - `sum()`, `mean()`, `min()`, `max()`
    
    - Axis argument

    - Logical Operations
    
    - Sorting function - `sort()`, `argsort()`

       
       
- **Use Case: Fitness Data analysis**
    - Loading data set and EDA using numpy
    - `np.argmax()`




In [2]:
import numpy as np

In [3]:
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

Downloading...
From: https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
To: /Users/nikhilsanghi/Downloads/01_dsml-course-main-live/batches/1_Aug_Beg_Mon/03_Numpy_2_cont/survey.txt
100%|██████████████████████████████████████| 2.55k/2.55k [00:00<00:00, 2.86MB/s]


In [4]:
score=np.loadtxt("/Users/nikhilsanghi/Downloads/01_dsml-course-main-live/batches/1_Aug_Beg_Mon/02_Numpy_2/survey.txt",dtype='int')

In [5]:
score

array([ 7, 10,  5, ...,  5,  9, 10])

In [6]:
type(None)

NoneType

In [17]:
arr=np.empty(shape=score.shape,dtype="<U20")
arr

array(['', '', '', ..., '', '', ''], dtype='<U20')

In [15]:
# np.array(["scaler","academy","dsml"],dtype="<U5")

In [16]:
# np.array(["scaler","academy","dsml","dhsujdlhfadskfhdskalfhk"],dtype="U10")

In [19]:
score<7

array([False, False,  True, ...,  True, False, False])

In [ ]:
score[score<7]

In [20]:
arr[score<7]="detractors"

In [21]:
arr

array(['', '', 'detractors', ..., 'detractors', '', ''], dtype='<U20')

In [22]:
score

array([ 7, 10,  5, ...,  5,  9, 10])

In [24]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [25]:
a<3

array([ True,  True, False, False, False])

In [27]:
b=np.empty(shape=a.shape,dtype="i4")
b


array([  0,   0,   0,   0, 101], dtype=int32)

In [29]:
a[a<3]=0

In [30]:
a

array([0, 0, 3, 4, 5])

In [31]:
b[a<3]=200

In [32]:
b

array([200, 200,   0,   0, 101], dtype=int32)

In [33]:
arr[score>8]="promotors"

In [34]:
arr[(score==7) | (score==8)]="passives"

In [35]:
arr

array(['passives', 'promotors', 'detractors', ..., 'detractors',
       'promotors', 'promotors'], dtype='<U20')

In [36]:
score

array([ 7, 10,  5, ...,  5,  9, 10])

In [38]:
a=score[:10]

In [39]:
a

array([ 7, 10,  5,  9,  9,  4,  7,  9,  9,  9])

In [40]:
b=np.empty(shape=a.shape,dtype="U20")
b

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U20')

In [41]:
a>7

array([False,  True, False,  True,  True, False, False,  True,  True,
        True])

In [43]:
b[a<7]="detractors"

In [45]:
b


array(['', '', 'detractors', '', '', 'detractors', '', '', '', ''],
      dtype='<U20')

In [46]:
a

array([ 7, 10,  5,  9,  9,  4,  7,  9,  9,  9])

In [47]:
b[a>8]="promotors"

In [48]:
b

array(['', 'promotors', 'detractors', 'promotors', 'promotors',
       'detractors', '', 'promotors', 'promotors', 'promotors'],
      dtype='<U20')

In [49]:
b[(a==7) | (a==8)]="passives"

In [50]:
b

array(['passives', 'promotors', 'detractors', 'promotors', 'promotors',
       'detractors', 'passives', 'promotors', 'promotors', 'promotors'],
      dtype='<U20')

In [51]:
arr

array(['passives', 'promotors', 'detractors', ..., 'detractors',
       'promotors', 'promotors'], dtype='<U20')

In [52]:
np.unique(arr)

array(['detractors', 'passives', 'promotors'], dtype='<U20')

In [53]:
np.unique(score)

array([ 1,  4,  5,  7,  8,  9, 10])

In [57]:
result=np.unique(arr,return_counts=True)
result

(array(['detractors', 'passives', 'promotors'], dtype='<U20'),
 array([332, 226, 609]))

In [56]:
arr.unique()÷

SyntaxError: invalid character '÷' (U+00F7) (2752609629.py, line 1)

In [65]:
dictionary={}
dictionary[result[0][0]]=result[1][0]
dictionary[result[0][1]]=result[1][1]
dictionary[result[0][2]]=result[1][2]

In [66]:
result[1][0]

332

In [67]:
dictionary

{'detractors': 332, 'passives': 226, 'promotors': 609}

In [68]:
# 2d numpy arrays

In [69]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
# np.array([[1,2,3],[4,5,6],[7,8,9,10]])


In [72]:
a.ndim

2

In [74]:
a.shape

(3, 3)

In [75]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
b.shape

(2, 3)

In [77]:
b.ndim

2

In [78]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
a.size

9

In [80]:
b.size

6

In [81]:
c=np.array([1,2,3,4])
c

array([1, 2, 3, 4])

In [82]:
c.size

4

In [83]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
a.size

9

In [88]:
a.shape


(3, 3)

In [85]:
a.shape[0]

3

In [86]:
a.shape[1]

3

In [87]:
a.shape[0]*a.shape[1]

9

In [89]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
b.shape

(2, 3)

In [91]:
b.size

6

In [92]:
b.shape[0]

2

In [93]:
b.shape[1]

3

In [94]:
b.shape[0]*b.shape[1]

6

In [95]:
d=np.array([[1,2,3,4]])
e=np.array([1,2,3,4])

In [100]:
d

array([[1, 2, 3, 4]])

In [96]:
d.ndim

2

In [97]:
e.ndim

1

In [98]:
d.shape

(1, 4)

In [99]:
e.shape


(4,)

In [102]:
a=np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [103]:
a.shape

(12,)

In [ ]:
# a.reshape(shape=())

In [ ]:
# a.reshape(x,y...)

In [ ]:
#  a.reshape((x,y...)) # preferrable

In [104]:
a.reshape((1,12))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [105]:
a.reshape((12,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [111]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [106]:
a.reshape((2,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [107]:
a.reshape((6,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [110]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [108]:
a.reshape((3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [109]:
a.reshape((4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [112]:
a.reshape((5,4))

ValueError: cannot reshape array of size 12 into shape (5,4)

In [114]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# a.reshape((-1,c))
# a.reshape((r,-1))

# a.reshape((-1,-1))

In [113]:
a.reshape((-1,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [115]:
a.reshape((2,-1))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [116]:
a.reshape((-1,-1))

ValueError: can only specify one unknown dimension

In [117]:
a.reshape((-1,5))

ValueError: cannot reshape array of size 12 into shape (5)

In [119]:
a=a.reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [121]:
len(a)

3

In [120]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [122]:
a.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [123]:
a=np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [124]:
a.T

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [125]:
a=np.arange(1,13).reshape((1,12))
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [126]:
a.T

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [129]:
a=a.reshape((3,4))
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [130]:
a.reshape((12,))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [131]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [132]:
a.reshape((1,-1))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [133]:
a.reshape((-1,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [134]:
a.reshape((a.size,))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [135]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [137]:
a[1][1] # not recommended in DS

6

In [139]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [138]:
a[1,1]

6

In [140]:
a[2,2]

11

In [141]:
a[-2,-1]

8

In [142]:
a[1,-1]

8

In [143]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# a[rows,columns]

In [144]:
a[[0,1,1],[1,2,3]] #recommended

array([2, 7, 8])

In [145]:
a[(0,1,1),(1,2,3)] # not recommended 

array([2, 7, 8])

In [ ]:
a[[0,1,1],[1,2,3]]

In [146]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [147]:
a[[-3,-2,-2],[-3,-2,-1]]

array([2, 7, 8])

In [148]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [149]:
a=np.arange(1,13).reshape((3,4))
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [151]:
a=a.flatten()
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [154]:
a=a.reshape((4,3))

In [155]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [159]:
a[[0,1,2],[-2,-1,-1]]

array([2, 6, 9])