In [1]:
print("Welcome to Numpy-4")

Welcome to Numpy-4


- **Matrix Multiplication**✅
    - `matmul()`, `@`, `dot()`✅
    

- **Vectorization**✅
    - `np.vectorize()`✅
    
    
- **Broadcasting**✅


- **Array splitting and Merging**
    - Splitting arrays - `split()`, `hsplit()`, `vsplit()`
    - Merging Arrays - `hstack()`, `vstack()`
    

- **Dimension Expansion and Reduction**✅
    - `np.expand_dims()`✅
    - `np.newaxis`✅
    - `np.sqeeze()`✅


- **Shallow vs Deep Copy**✅
    - `view()`✅
    - `copy()`✅
    - `copy.deepcopy()`✅


- **Dimension Expansion and Reduction**
    - `np.expand_dims()`
    - `np.newaxis`
    - `np.sqeeze()`

In [2]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [3]:
a.shape

(6,)

In [4]:
a.ndim

1

In [8]:
np.expand_dims(a,axis=0).shape

(1, 6)

In [13]:
np.expand_dims(a,axis=0)

array([[0, 1, 2, 3, 4, 5]])

In [14]:
np.expand_dims(a,axis=1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [9]:
np.expand_dims(a,axis=1).shape

(6, 1)

In [11]:
# np.expand_dims(a,axis=2).shape

In [15]:
a

array([0, 1, 2, 3, 4, 5])

In [16]:
a

array([0, 1, 2, 3, 4, 5])

In [18]:
a.reshape((6,1,1,1,1,1,1,1))

array([[[[[[[[0]]]]]]],






       [[[[[[[1]]]]]]],






       [[[[[[[2]]]]]]],






       [[[[[[[3]]]]]]],






       [[[[[[[4]]]]]]],






       [[[[[[[5]]]]]]]])

In [20]:
# a.reshape((6,1,1,1,1,1,1,2))

In [21]:
a=np.arange(1,13).reshape((3,4))
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
a.ndim

2

In [23]:
a.shape

(3, 4)

In [24]:
np.expand_dims(a,axis=0).shape

(1, 3, 4)

In [25]:
np.expand_dims(a,axis=1).shape

(3, 1, 4)

In [26]:
np.expand_dims(a,axis=2).shape

(3, 4, 1)

In [27]:
np.expand_dims(a,axis=0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [28]:
np.expand_dims(a,axis=1)

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [29]:
np.expand_dims(a,axis=2)

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]]])

In [30]:
a=np.arange(1,25).reshape((2,3,4))
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [31]:
a.shape

(2, 3, 4)

In [32]:
a.ndim

3

In [33]:
np.expand_dims(a,axis=0).shape

(1, 2, 3, 4)

In [34]:
np.expand_dims(a,axis=1).shape

(2, 1, 3, 4)

In [35]:
np.expand_dims(a,axis=2).shape

(2, 3, 1, 4)

In [36]:
np.expand_dims(a,axis=3).shape

(2, 3, 4, 1)

In [37]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [38]:
a.shape

(6,)

In [39]:
a[np.newaxis,:].shape

(1, 6)

In [40]:
a[:,np.newaxis].shape

(6, 1)

In [41]:
a[:,np.newaxis,np.newaxis,np.newaxis].shape

(6, 1, 1, 1)

In [42]:
a[:,np.newaxis,np.newaxis,np.newaxis]

array([[[[0]]],


       [[[1]]],


       [[[2]]],


       [[[3]]],


       [[[4]]],


       [[[5]]]])

In [43]:
a.shape

(6,)

In [45]:
a[np.newaxis,np.newaxis,:,np.newaxis,np.newaxis,np.newaxis,np.newaxis,np.newaxis,np.newaxis,np.newaxis].shape

(1, 1, 6, 1, 1, 1, 1, 1, 1, 1)

In [49]:
# a[np.newaxis,np.newaxis,:,np.newaxis,np.newaxis,np.newaxis,np.newaxis,np.newaxis,np.newaxis,np.newaxis]

In [48]:
# a.reshape((1,1,1,1,1,3,2,1,1,1,1,1))

In [51]:
b=np.arange(1,13).reshape((3,4))
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
b.shape

(3, 4)

In [53]:
b.ndim

2

In [55]:
b[np.newaxis,:].shape

(1, 3, 4)

In [56]:
b[:,np.newaxis].shape

(3, 1, 4)

In [57]:
b[:,np.newaxis,np.newaxis].shape

(3, 1, 1, 4)

In [58]:
b[:,np.newaxis,:,np.newaxis].shape

(3, 1, 4, 1)

In [59]:
b[:,:,np.newaxis,np.newaxis].shape

(3, 4, 1, 1)

In [61]:
# b[:,:,np.newaxis,np.newaxis,:].shape

In [62]:
c=np.arange(1,25).reshape((2,3,4))
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [63]:
c.ndim

3

In [64]:
c.shape

(2, 3, 4)

In [66]:
c[np.newaxis,:].shape

(1, 2, 3, 4)

In [67]:
c[np.newaxis,:,np.newaxis].shape

(1, 2, 1, 3, 4)

In [68]:
c[np.newaxis,:,:,np.newaxis].shape

(1, 2, 3, 1, 4)

In [69]:
c[:,np.newaxis,:,np.newaxis].shape

(2, 1, 3, 1, 4)

In [70]:
c[:,:,np.newaxis,:,np.newaxis].shape

(2, 3, 1, 4, 1)

In [71]:
c[:,:,np.newaxis,:,np.newaxis,np.newaxis,np.newaxis].shape

(2, 3, 1, 4, 1, 1, 1)

In [72]:
c[:,:,None,:,None,None,None].shape

(2, 3, 1, 4, 1, 1, 1)

In [73]:
np.squeeze?


In [75]:
a

array([0, 1, 2, 3, 4, 5])

In [76]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [77]:
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [78]:
c.shape

(2, 3, 4)

In [85]:
d=c.reshape((1,2,1,3,1,4,1,1,1))
d.shape

(1, 2, 1, 3, 1, 4, 1, 1, 1)

In [84]:
np.squeeze(d).shape

(2, 3, 4)

In [87]:
np.squeeze(d,axis=2).shape

(1, 2, 3, 1, 4, 1, 1, 1)

In [90]:
# np.squeeze(d,axis=1).shape

In [93]:
np.squeeze(d,axis=(4,6,7)).shape

(1, 2, 1, 3, 4, 1)

In [91]:
np.squeeze?

In [94]:
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [95]:
c.shape

(2, 3, 4)

In [97]:
np.squeeze(c).shape

(2, 3, 4)

In [98]:
d.shape

(1, 2, 1, 3, 1, 4, 1, 1, 1)

In [99]:
np.squeeze?

- **Shallow vs Deep Copy**
    - `view()`
    - `copy()`
    - `copy.deepcopy()`

In [100]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [101]:
b=a.reshape((2,2))
b

array([[1, 2],
       [3, 4]])

In [102]:
a[0]=100
a

array([100,   2,   3,   4])

In [103]:
b

array([[100,   2],
       [  3,   4]])

In [104]:
b[1,1]=99
b

array([[100,   2],
       [  3,  99]])

In [105]:
a

array([100,   2,   3,  99])

In [106]:
c=a[::2]

In [107]:
c

array([100,   3])

In [109]:
c[1]=999
c

array([100, 999])

In [110]:
a

array([100,   2, 999,  99])

In [111]:
b

array([[100,   2],
       [999,  99]])

In [121]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [113]:
x=a+2
x

array([3, 4, 5, 6])

In [114]:
a

array([1, 2, 3, 4])

In [116]:
x

array([3, 4, 5, 6])

In [117]:
a[0]=100

In [118]:
a


array([100,   2,   3,   4])

In [119]:
x

array([3, 4, 5, 6])

In [122]:
y=a+0
y

array([1, 2, 3, 4])

In [123]:
a

array([1, 2, 3, 4])

In [124]:
y

array([1, 2, 3, 4])

In [125]:
a[0]=100

In [126]:
a

array([100,   2,   3,   4])

In [127]:
y

array([1, 2, 3, 4])

In [128]:
q=a*1
q

array([100,   2,   3,   4])

In [129]:
a=np.array([1,2,3,4])
b=a.reshape((2,2))
c=a[::2]
d=a+0
e=a*1

In [130]:
np.shares_memory(a,b)

True

In [131]:
np.shares_memory(a,c)

True

In [132]:
np.shares_memory(a,d)

False

In [133]:
np.shares_memory(a,e)

False

In [134]:
np.shares_memory(b,c)

True

In [135]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [136]:
b=a.view()
b

array([1, 2, 3, 4])

In [137]:
b[0]=100
b

array([100,   2,   3,   4])

In [138]:
a

array([100,   2,   3,   4])

In [139]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [140]:
c=a.copy()
c

array([1, 2, 3, 4])

In [141]:
a[0]=100

In [142]:
a

array([100,   2,   3,   4])

In [143]:
c

array([1, 2, 3, 4])

In [144]:
np.shares_memory(a,c)

False

In [145]:
a=np.array([1,"m",[1,2,3]],dtype="object")
a

array([1, 'm', list([1, 2, 3])], dtype=object)

In [146]:
b=a.copy()
b

array([1, 'm', list([1, 2, 3])], dtype=object)

In [147]:
np.shares_memory(a,b)

False

In [149]:
a[2][0]=100
a

array([1, 'm', list([100, 2, 3])], dtype=object)

In [150]:
b

array([1, 'm', list([100, 2, 3])], dtype=object)

In [152]:
b[2][2]=99

In [153]:
b

array([1, 'm', list([100, 2, 99])], dtype=object)

In [154]:
a

array([1, 'm', list([100, 2, 99])], dtype=object)

In [156]:
a=np.array([1,"m",[1,2,3]],dtype="object")
a

array([1, 'm', list([1, 2, 3])], dtype=object)

In [155]:
import copy

In [157]:
b=copy.deepcopy(a)
b

array([1, 'm', list([1, 2, 3])], dtype=object)

In [159]:
a[2][0]=100

In [160]:
a

array([1, 'm', list([100, 2, 3])], dtype=object)

In [161]:
b

array([1, 'm', list([1, 2, 3])], dtype=object)

In [164]:
a=np.arange(1,13).reshape((3,4))
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [171]:
# np.expand_dims(a,axis = 0).expand_dims(a,axis=2)

In [170]:
np.expand_dims(np.expand_dims(a,axis = 0),axis=2).shape

(1, 3, 1, 4)