In [1]:
print("Welcome to Numpy-2-Cont")

Welcome to Numpy-2-Cont


## Agenda

- **Usecase: calculate NPS**✅
    - loading data: `np.loadtxt()`✅
    - `np.empty()`✅
    - `np.unique()`✅


- **Introduction to use case**✅

    
- **2-D arrays (Matrices)**✅
    - `reshape()`
    - 2 Questions✅
    - Transpose✅
    - Converting Matrix back to Vector - `flatten()`✅

- **Indexing and Slicing on 2D** ✅
    - Indexing✅

    - Slicing✅

    - Masking (Fancy Indexing)✅




- **Universal Functions (ufunc) on 2D**✅
    - Aggregate Function/ Reduction functions - `sum()`, `mean()`, `min()`, `max()`✅
    
    - Axis argument✅

    - Logical Operations✅
    
    - Sorting function - `sort()`, `argsort()`✅

       
       
- **Use Case: Fitness Data analysis**
    - Loading data set and EDA using numpy
    - `np.argmax()`✅




In [2]:
import numpy as np

In [7]:
a=np.arange(1,13)
a.shape

(12,)

In [5]:
a.shape=(3,4)

In [6]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
a.reshape((3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [18]:
b=a.reshape((3,4,1,1,1,1,1))

In [20]:
b

array([[[[[[[ 1]]]]],




        [[[[[ 2]]]]],




        [[[[[ 3]]]]],




        [[[[[ 4]]]]]],





       [[[[[[ 5]]]]],




        [[[[[ 6]]]]],




        [[[[[ 7]]]]],




        [[[[[ 8]]]]]],





       [[[[[[ 9]]]]],




        [[[[[10]]]]],




        [[[[[11]]]]],




        [[[[[12]]]]]]])

In [19]:
b.ndim

7

In [21]:
b.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [22]:
b

array([[[[[[[ 1]]]]],




        [[[[[ 2]]]]],




        [[[[[ 3]]]]],




        [[[[[ 4]]]]]],





       [[[[[[ 5]]]]],




        [[[[[ 6]]]]],




        [[[[[ 7]]]]],




        [[[[[ 8]]]]]],





       [[[[[[ 9]]]]],




        [[[[[10]]]]],




        [[[[[11]]]]],




        [[[[[12]]]]]]])

In [ ]:
# slicing 

In [53]:
a=np.arange(1,13).reshape((3,4))
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
# a[ rows, columns ]

In [26]:
a[ ::,:: ]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
a[ 1: : , 1: : ]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [28]:
a[ 1: : , 1: : 2]

array([[ 6,  8],
       [10, 12]])

In [29]:
a[ 1: : -1, 1: : 2]

array([[6, 8],
       [2, 4]])

In [30]:
a[ 2: : -1, : : 2]

array([[ 9, 11],
       [ 5,  7],
       [ 1,  3]])

In [31]:
a[ 2: : -2, : : -2]

array([[12, 10],
       [ 4,  2]])

In [32]:
a[-1:-3:-1 , 2::-2]

array([[11,  9],
       [ 7,  5]])

In [33]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
#masking

In [35]:
a<7

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [36]:
a[a<7]

array([1, 2, 3, 4, 5, 6])

In [38]:
a[a%3==0]

array([ 3,  6,  9, 12])

In [39]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
a%3==0

array([[False, False,  True, False],
       [False,  True, False, False],
       [ True, False, False,  True]])

In [41]:
a[a%3==0]

array([ 3,  6,  9, 12])

In [42]:
a[~(a%3==0)]

array([ 1,  2,  4,  5,  7,  8, 10, 11])

In [43]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
(a%2==0) & (a>4)

array([[False, False, False, False],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [45]:
a[(a%2==0) & (a>4)]

array([ 6,  8, 10, 12])

In [47]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
a[(a%2==0) & (a>4)]=100

In [50]:
a

array([[  1,   2,   3,   4],
       [  5, 100,   7, 100],
       [  9, 100,  11, 100]])

In [57]:
a[[a<7]]

/var/folders/hd/9z4dczb56dj54lb7q8w7s4zw0000gn/T/ipykernel_2144/1154070667.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  a[[a<7]]


array([1, 2, 3, 4, 5, 6])

In [54]:
a[(a<7)]

array([1, 2, 3, 4, 5, 6])

In [46]:
# Universal functions

In [58]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
np.sum(a)

78

In [60]:
np.min(a)

1

In [61]:
np.max(a)

12

In [62]:
np.mean(a)

6.5

In [63]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [64]:
np.sum(a,axis=0)

array([15, 18, 21, 24])

In [65]:
np.sum(a,axis=1)

array([10, 26, 42])

In [66]:
np.min(a,axis=0)

array([1, 2, 3, 4])

In [68]:
# np.min(a,axis=2)

In [69]:
np.min(a,axis=1)

array([1, 5, 9])

In [70]:
b=np.arange(1,13)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [71]:
np.min(b,axis=0)

1

In [87]:
# np.min(b,axis=1)

In [73]:
a=np.array([[10,2,99],[100,4,21],[32,5,12],[9,57,45]])
a

array([[ 10,   2,  99],
       [100,   4,  21],
       [ 32,   5,  12],
       [  9,  57,  45]])

In [74]:
np.sort(a,axis=1)

array([[  2,  10,  99],
       [  4,  21, 100],
       [  5,  12,  32],
       [  9,  45,  57]])

In [75]:
np.sort(a,axis=0)

array([[  9,   2,  12],
       [ 10,   4,  21],
       [ 32,   5,  45],
       [100,  57,  99]])

In [76]:
np.sort(a)

array([[  2,  10,  99],
       [  4,  21, 100],
       [  5,  12,  32],
       [  9,  45,  57]])

In [77]:
a


array([[ 10,   2,  99],
       [100,   4,  21],
       [ 32,   5,  12],
       [  9,  57,  45]])

In [78]:
np.min(a,axis=0)

array([ 9,  2, 12])

In [79]:
np.min(a,axis=1)

array([2, 4, 5, 9])

In [80]:
np.min(a)

2

In [81]:
a=np.arange(1,13).reshape((12,1))
a

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [82]:
np.max(a,axis=1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [83]:
np.max(a,axis=0)

array([12])

In [84]:
a=np.array([[10,2,99],[100,4,21],[32,5,12],[9,57,45]])
a

array([[ 10,   2,  99],
       [100,   4,  21],
       [ 32,   5,  12],
       [  9,  57,  45]])

In [85]:
np.max(a,axis=0)

array([100,  57,  99])

In [86]:
np.max(a,axis=1)

array([ 99, 100,  32,  57])

In [88]:
# logical operations


In [92]:
a=np.array([4,3,2,1])
b=np.array([1,2,3,4])
c=np.array([1,2,3,4,5])
print(a)
print(b)
print(c)

[4 3 2 1]
[1 2 3 4]
[1 2 3 4 5]


In [93]:
a>b

array([ True,  True, False, False])

In [95]:
# a>c

In [96]:
# np.any()  --> atleast 1 True value --> True
# np.all()  --> all the values must be True --> True

In [97]:
np.any(a>b)

True

In [98]:
a==b

array([False, False, False, False])

In [99]:
np.any(a==b)

False

In [100]:
np.all(a>b)

False

In [101]:
a=np.array([4,3,2,1])
b=np.array([1,2,3,4])
d=np.array([10,10,10,10])
print(a)
print(b)
print(d)

[4 3 2 1]
[1 2 3 4]
[10 10 10 10]


In [102]:
a<d

array([ True,  True,  True,  True])

In [103]:
np.all(a<d)

True

In [104]:
# np.where

In [115]:
a=np.array([-2,3,-1,4,9,10,-20,12,-13])
a

array([ -2,   3,  -1,   4,   9,  10, -20,  12, -13])

In [113]:
a[a<0]=-1
a[a>0]=1
a

array([-1,  1, -1,  1,  1,  1, -1,  1, -1])

In [114]:
a

array([-1,  1, -1,  1,  1,  1, -1,  1, -1])

In [116]:
a

array([ -2,   3,  -1,   4,   9,  10, -20,  12, -13])

In [117]:
np.where(a>0,+1,-1)

array([-1,  1, -1,  1,  1,  1, -1,  1, -1])

In [118]:
a

array([ -2,   3,  -1,   4,   9,  10, -20,  12, -13])

In [122]:
np.where(a<0,-1,a)

array([-1,  3, -1,  4,  9, 10, -1, 12, -1])

In [123]:
a

array([ -2,   3,  -1,   4,   9,  10, -20,  12, -13])

In [124]:
np.where(a>0)

(array([1, 3, 4, 5, 7]),)

In [125]:
a

array([ -2,   3,  -1,   4,   9,  10, -20,  12, -13])

In [165]:
a=np.arange(1,13).reshape((3,4))
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [166]:
np.where(a<7)

(array([0, 0, 0, 0, 1, 1]), array([0, 1, 2, 3, 0, 1]))

In [167]:
a[np.where(a<7)]

array([1, 2, 3, 4, 5, 6])

In [168]:
a[[0, 0, 0, 0, 1, 1],[0, 1, 2, 3, 0, 1]]

array([1, 2, 3, 4, 5, 6])

In [153]:
a=np.array([12,2,1,3,7,4,8,6])
a

array([12,  2,  1,  3,  7,  4,  8,  6])

In [129]:
np.max(a)

12

In [130]:
np.min(a)

1

In [131]:
np.argmax(a)

0

In [132]:
np.argmin(a)

2

In [133]:
a

array([12,  2,  1,  3,  7,  4,  8,  6])

In [134]:
np.sort(a)

array([ 1,  2,  3,  4,  6,  7,  8, 12])

In [135]:
np.argsort(a)

array([2, 1, 3, 5, 7, 4, 6, 0])

In [136]:
a

array([12,  2,  1,  3,  7,  4,  8,  6])

In [137]:
a[[2, 1, 3, 5, 7, 4, 6, 0]]

array([ 1,  2,  3,  4,  6,  7,  8, 12])

In [154]:
a

array([12,  2,  1,  3,  7,  4,  8,  6])

In [ ]:
[1,3,4,6]

In [155]:
a[[1,3,4,6]]

array([2, 3, 7, 8])

In [156]:
np.argsort(a)

array([2, 1, 3, 5, 7, 4, 6, 0])

In [157]:
a[[2, 1, 3, 5, 7, 4, 6, 0]]

array([ 1,  2,  3,  4,  6,  7,  8, 12])

In [158]:
np.argmax(a)

0

In [164]:
np.where(a == np.max(a))[0][0]

0

In [163]:
np.argmax(a) == np.where(a == np.max(a))[0][0]

True

In [139]:
# Questions

In [140]:
a=np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

b=np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])



In [142]:
print(np.all(a==b))

True


In [141]:
a==b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [144]:
a=np.array([[1, 2, 3],
 [4, 6, 6],
 [7, 8, 9]])

b=np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])



In [145]:
print(a)
print(b)

[[1 2 3]
 [4 6 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [147]:
print(np.any(a>b))

True


In [146]:
a>b

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [148]:
a = np.array([0,2,3])
b = np.array([1,3,5])

In [150]:
a >= b

array([False, False, False])

In [151]:
np.all(a >= b)

False

In [152]:
np.any(a >= b)

False

In [170]:
a=np.array([[10,2,99],[100,4,21],[32,5,12],[9,57,45]])
a

array([[ 10,   2,  99],
       [100,   4,  21],
       [ 32,   5,  12],
       [  9,  57,  45]])

In [171]:
a[:2,:].sum(axis=1)

array([111, 125])

In [173]:
a=np.array(['b','c','d','e','a'])
b=np.array([2,3,4,5,1])

In [174]:
np.sort(b)

array([1, 2, 3, 4, 5])

In [175]:
np.argsort(b)

array([4, 0, 1, 2, 3])

In [176]:
a[np.argsort(b)]

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

In [ ]:
r"\Users\nikhilsanghi\Downloads\01_dsml-course-main-live\batches\1_Aug_Beg_Mon\02_Numpy_2\survey.txt"