In [1]:
print("Welcome to Numpy-4_Cont")

Welcome to Numpy-4_Cont


## Agenda
- **Array splitting and Merging**
    - Splitting arrays - `split()`, `hsplit()`, `vsplit()` ✅
    - Merging Arrays - `hstack()`, `vstack()` ✅

In [2]:
import numpy as np

In [5]:
#1d 
a=np.arange(1,13)

In [6]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
np.split(a,3)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

In [8]:
np.split(a,2)

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])]

In [10]:
# np.split(a,5)

In [11]:
b=np.arange(1,14)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [15]:
np.split(b,13)

[array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([7]),
 array([8]),
 array([9]),
 array([10]),
 array([11]),
 array([12]),
 array([13])]

In [16]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [17]:
np.split(a,[3,5,7])

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([ 8,  9, 10, 11, 12])]

In [18]:
np.split(a,[2,6,8])

[array([1, 2]), array([3, 4, 5, 6]), array([7, 8]), array([ 9, 10, 11, 12])]

In [19]:
np.split(a,[5,3,7])

[array([1, 2, 3, 4, 5]),
 array([], dtype=int64),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10, 11, 12])]

In [20]:
np.split(a,[-7,-9,-5])

[array([1, 2, 3, 4, 5]),
 array([], dtype=int64),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10, 11, 12])]

In [21]:
# 2d

In [22]:
a=np.arange(1,49).reshape((6,8))
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48]])

In [25]:
np.split(a,3)

[array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16]]),
 array([[17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32]]),
 array([[33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48]])]

In [26]:
np.split(a,3,axis=0)

[array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16]]),
 array([[17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32]]),
 array([[33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48]])]

In [27]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48]])

In [28]:
np.split(a,2,axis=0)

[array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29, 30, 31, 32],
        [33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48]])]

In [29]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48]])

In [31]:
# np.split(a,4,axis=0)

In [32]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48]])

In [34]:
np.split(a, 4,axis=1)

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26],
        [33, 34],
        [41, 42]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28],
        [35, 36],
        [43, 44]]),
 array([[ 5,  6],
        [13, 14],
        [21, 22],
        [29, 30],
        [37, 38],
        [45, 46]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24],
        [31, 32],
        [39, 40],
        [47, 48]])]

In [35]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48]])

In [36]:
np.split(a,[2,4],axis=0)

[array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16]]),
 array([[17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32]]),
 array([[33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48]])]

In [37]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48]])

In [38]:
np.split(a,[2],axis=0)

[array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16]]),
 array([[17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32],
        [33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48]])]

In [39]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48]])

In [ ]:
# np.split(a,[2,],axis=0)

In [41]:
np.split(a,[1],axis=0)

[array([[1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32],
        [33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48]])]

In [42]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48]])

In [43]:
np.split(a,[2,3],axis=1)

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26],
        [33, 34],
        [41, 42]]),
 array([[ 3],
        [11],
        [19],
        [27],
        [35],
        [43]]),
 array([[ 4,  5,  6,  7,  8],
        [12, 13, 14, 15, 16],
        [20, 21, 22, 23, 24],
        [28, 29, 30, 31, 32],
        [36, 37, 38, 39, 40],
        [44, 45, 46, 47, 48]])]

In [44]:
# np.vsplit()
# np.hsplit()

In [45]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48]])

In [46]:
np.vsplit(a,3)

[array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16]]),
 array([[17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32]]),
 array([[33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48]])]

In [47]:
np.vsplit(a,[2,3])

[array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16]]),
 array([[17, 18, 19, 20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29, 30, 31, 32],
        [33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48]])]

In [48]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48]])

In [49]:
np.hsplit(a,4)

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26],
        [33, 34],
        [41, 42]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28],
        [35, 36],
        [43, 44]]),
 array([[ 5,  6],
        [13, 14],
        [21, 22],
        [29, 30],
        [37, 38],
        [45, 46]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24],
        [31, 32],
        [39, 40],
        [47, 48]])]

In [51]:
# np.hsplit(a,3)

In [52]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48]])

In [53]:
np.hsplit(a,[2,3])

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26],
        [33, 34],
        [41, 42]]),
 array([[ 3],
        [11],
        [19],
        [27],
        [35],
        [43]]),
 array([[ 4,  5,  6,  7,  8],
        [12, 13, 14, 15, 16],
        [20, 21, 22, 23, 24],
        [28, 29, 30, 31, 32],
        [36, 37, 38, 39, 40],
        [44, 45, 46, 47, 48]])]

In [55]:
a=np.arange(1,25).reshape((2,3,4))
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [56]:
np.split(a,2,axis=0)

[array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]]),
 array([[[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])]

In [58]:
np.split(a,3,axis=1)

[array([[[ 1,  2,  3,  4]],
 
        [[13, 14, 15, 16]]]),
 array([[[ 5,  6,  7,  8]],
 
        [[17, 18, 19, 20]]]),
 array([[[ 9, 10, 11, 12]],
 
        [[21, 22, 23, 24]]])]

In [60]:
np.split(a,2,axis=2)

[array([[[ 1,  2],
         [ 5,  6],
         [ 9, 10]],
 
        [[13, 14],
         [17, 18],
         [21, 22]]]),
 array([[[ 3,  4],
         [ 7,  8],
         [11, 12]],
 
        [[15, 16],
         [19, 20],
         [23, 24]]])]

In [61]:
# Stacking

In [62]:
# 1d with 1d
a=np.arange(1,5)
b=np.arange(1,5)

a

array([1, 2, 3, 4])

In [63]:
b

array([1, 2, 3, 4])

In [65]:
np.hstack((a,b))

array([1, 2, 3, 4, 1, 2, 3, 4])

In [66]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [67]:
c=np.arange(1,6)
c

array([1, 2, 3, 4, 5])

In [70]:
# np.vstack((a,c))

In [71]:
a=np.arange(1,5).reshape((1,4))
b=np.arange(1,5).reshape((1,4))
print(a)
print(b)

[[1 2 3 4]]
[[1 2 3 4]]


In [72]:
np.vstack((a,b))


array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [75]:

np.hstack((a,b))

array([[1, 2, 3, 4, 1, 2, 3, 4]])

In [76]:
a=np.arange(1,13).reshape((3,4))
b=np.arange(1,13).reshape((3,4))
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [77]:
np.hstack((a,b))

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12]])

In [78]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [79]:
a=np.arange(1,13).reshape((3,4))
b=np.arange(1,5).reshape((1,4))
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]]


In [81]:
# np.hstack((a,b))

In [82]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [83]:
a=np.arange(1,13).reshape((3,4))
b=np.arange(1,5)
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]


In [85]:
# np.hstack((a,b))

In [86]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [87]:
a=np.arange(1,5)
b=np.arange(1,5)
print(a)
print(b)

[1 2 3 4]
[1 2 3 4]


In [88]:
np.concatenate((a,b))

array([1, 2, 3, 4, 1, 2, 3, 4])

In [89]:
np.concatenate((a,b),axis=0)

array([1, 2, 3, 4, 1, 2, 3, 4])

In [91]:
# np.concatenate((a,b),axis=1)

In [97]:
a=np.arange(1,13).reshape((3,4))
b=np.arange(1,5)
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]


In [99]:
# np.concatenate((a,b),axis=1)

In [100]:
a=np.arange(1,5)
b=np.arange(1,5)
print(a)
print(b)

[1 2 3 4]
[1 2 3 4]


In [101]:
np.stack((a,b))

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [103]:
np.stack((a,b),axis=1)

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [104]:
np.stack((a,b),axis=0)

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [105]:
a=np.arange(1,5).reshape((1,4))
b=np.arange(1,5).reshape((1,4))
print(a)
print(b)

[[1 2 3 4]]
[[1 2 3 4]]


In [106]:
np.stack((a,b),axis=0)

array([[[1, 2, 3, 4]],

       [[1, 2, 3, 4]]])

In [107]:
np.stack((a,b),axis=1)

array([[[1, 2, 3, 4],
        [1, 2, 3, 4]]])